# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\scoreboardv.2.2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    #
    # FUNCTIONS
    #

    def addOneTeamA(self):
        score = int(self.lblTeamA_score.text())
        score += 1
        self.lblTeamA_score.setText(str(score))

    def addTwoTeamA(self):
        score = int(self.lblTeamA_score.text())
        score += 2
        self.lblTeamA_score.setText(str(score))

    def addThreeTeamA(self):
        score = int(self.lblTeamA_score.text())
        score += 3
        self.lblTeamA_score.setText(str(score))

    def correctionTeamA(self):
        score = int(self.lblTeamA_score.text())
        if score > 0:
            score -= 1
            self.lblTeamA_score.setText(str(score))

    def addOneTeamB(self):
        score = int(self.lblTeamB_score.text())
        score += 1
        self.lblTeamB_score.setText(str(score))

    def addTwoTeamB(self):
        score = int(self.lblTeamB_score.text())
        score += 2
        self.lblTeamB_score.setText(str(score))

    def addThreeTeamB(self):
        score = int(self.lblTeamB_score.text())
        score += 3
        self.lblTeamB_score.setText(str(score))

    def correctionTeamB(self):
        score = int(self.lblTeamB_score.text())
        if score > 0:
            score -= 1
            self.lblTeamB_score.setText(str(score))

    def TO(self):
        self.lblPer.setText('TO')

    def Per(self):
        self.lblPer.setText(str(0))

    def addOnePer(self):
        try:
            per = int(self.lblPer.text())
            if per < 4:
                per += 1
                self.lblPer.setText(str(per))
        except:
            self.lblPer.setText(str(0))

    def minusOnePer(self):
        try:
            per = int(self.lblPer.text())
            if per > 0:
                per -= 1
                self.lblPer.setText(str(per))
        except:
            self.lblPer.setText(str(0))

    def addNamesAndLogos(self):
        leftTeam = self.lTeamName.toPlainText()
        rightTeam = self.rTeamName.toPlainText()
        leftTeamLogoDir = self.lTeamLogo.toPlainText().replace('\\', '/')
        rightTeamLogoDir = self.rTeamLogo.toPlainText().replace('\\', '/')

        if len(leftTeam) < 3:
            self.lblTeamA_name.setText(leftTeam.upper()[:len(leftTeam)])
        else:
            self.lblTeamA_name.setText(leftTeam.upper()[:3])
        if len(rightTeam) < 6:
            self.lblTeamB_name.setText(rightTeam.upper()[:len(rightTeam)])
        else:
            self.lblTeamB_name.setText(rightTeam.upper()[:6])

        try:
            self.lblTeamA_logo.setStyleSheet(f"background-image: url({leftTeamLogoDir});\n"
                                            "background-repeat: no-repeat;\n"
                                            "background-position: center;")
        except:
            self.lblTeamA_logo.setText('ERROR')
        try:
            self.lblTeamB_logo.setStyleSheet(f"background-image: url({rightTeamLogoDir});\n"
                                            "background-repeat: no-repeat;\n"
                                            "background-position: center;")
        except:
            self.lblTeamA_logo.setText('ERROR')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 450)
        MainWindow.setMinimumSize(QtCore.QSize(660, 50))
        MainWindow.setMaximumSize(QtCore.QSize(660, 450))
        MainWindow.setStyleSheet("background-color: rgb(80, 80, 80);\n"
                                 "border-radius: 20px;")
        self.main = QtWidgets.QWidget(MainWindow)
        self.main.setMaximumSize(QtCore.QSize(16777215, 450))
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(9, 9, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.main)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.teamA_logo = QtWidgets.QFrame(self.main_frame)
        self.teamA_logo.setMinimumSize(QtCore.QSize(50, 30))
        self.teamA_logo.setMaximumSize(QtCore.QSize(50, 30))
        self.teamA_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamA_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamA_logo.setObjectName("teamA_logo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.teamA_logo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTeamA_logo = QtWidgets.QLabel(self.teamA_logo)
        self.lblTeamA_logo.setMaximumSize(QtCore.QSize(50, 30))
        self.lblTeamA_logo.setStyleSheet("background-image: url();\n"
                                         "background-repeat: no-repeat;\n"
                                         "background-position: center;")
        self.lblTeamA_logo.setText("")
        self.lblTeamA_logo.setObjectName("lblTeamA_logo")
        self.horizontalLayout_3.addWidget(self.lblTeamA_logo)
        self.horizontalLayout_2.addWidget(self.teamA_logo)
        self.teamA_name = QtWidgets.QFrame(self.main_frame)
        self.teamA_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.teamA_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamA_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamA_name.setObjectName("teamA_name")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.teamA_name)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblTeamA_name = QtWidgets.QLabel(self.teamA_name)
        self.lblTeamA_name.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTeamA_name.setFont(font)
        self.lblTeamA_name.setStyleSheet("margin-top: -30px;\n"
                                         "color: rgb(240, 240, 240);\n"
                                         "padding-bottom: 5px;\n"
                                         "border-radius: 10px;\n"
                                         "background-color: rgb(40, 40, 40); padding-left: 4px;")
        self.lblTeamA_name.setText("")
        self.lblTeamA_name.setObjectName("lblTeamA_name")
        self.horizontalLayout_4.addWidget(self.lblTeamA_name)
        self.horizontalLayout_2.addWidget(self.teamA_name)
        self.teamA_score = QtWidgets.QFrame(self.main_frame)
        self.teamA_score.setMaximumSize(QtCore.QSize(80, 16777215))
        self.teamA_score.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamA_score.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamA_score.setObjectName("teamA_score")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.teamA_score)
        self.horizontalLayout_7.setContentsMargins(2, 0, 1, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblTeamA_score = QtWidgets.QLabel(self.teamA_score)
        font = QtGui.QFont()
        font.setFamily("QuiverItal")
        font.setPointSize(22)
        self.lblTeamA_score.setFont(font)
        self.lblTeamA_score.setStyleSheet("color: rgb(200, 200, 200);\n"
                                          "background-color: rgb(40, 40, 40); border-radius: 10px; padding-right: 10px; padding-bottom: 5px;")
        self.lblTeamA_score.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblTeamA_score.setObjectName("lblTeamA_score")
        self.horizontalLayout_7.addWidget(self.lblTeamA_score)
        self.horizontalLayout_2.addWidget(self.teamA_score)
        self.teamB_score = QtWidgets.QFrame(self.main_frame)
        self.teamB_score.setMinimumSize(QtCore.QSize(0, 0))
        self.teamB_score.setMaximumSize(QtCore.QSize(80, 16777215))
        self.teamB_score.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamB_score.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamB_score.setObjectName("teamB_score")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.teamB_score)
        self.horizontalLayout_8.setContentsMargins(1, 0, 2, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblTeamB_score = QtWidgets.QLabel(self.teamB_score)
        font = QtGui.QFont()
        font.setFamily("QuiverItal")
        font.setPointSize(22)
        self.lblTeamB_score.setFont(font)
        self.lblTeamB_score.setStyleSheet("color: rgb(200, 200, 200);\n"
                                          "background-color: rgb(40, 40, 40); border-radius: 10px; padding-left: 10px; padding-bottom: 5px;")
        self.lblTeamB_score.setObjectName("lblTeamB_score")
        self.horizontalLayout_8.addWidget(self.lblTeamB_score)
        self.horizontalLayout_2.addWidget(self.teamB_score)
        self.teamB_name = QtWidgets.QFrame(self.main_frame)
        self.teamB_name.setMaximumSize(QtCore.QSize(140, 16777215))
        self.teamB_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamB_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamB_name.setObjectName("teamB_name")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.teamB_name)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblTeamB_name = QtWidgets.QLabel(self.teamB_name)
        self.lblTeamB_name.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTeamB_name.setFont(font)
        self.lblTeamB_name.setStyleSheet("margin-top: -30px;\n"
                                         "color: rgb(240, 240, 240);\n"
                                         "padding-bottom: 5px;\n"
                                         "border-radius: 10px;\n"
                                         "background-color: rgb(40, 40, 40); padding-left: 4px;")
        self.lblTeamB_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTeamB_name.setObjectName("lblTeamB_name")
        self.horizontalLayout_5.addWidget(self.lblTeamB_name)
        self.horizontalLayout_2.addWidget(self.teamB_name)
        self.teamB_logo = QtWidgets.QFrame(self.main_frame)
        self.teamB_logo.setMinimumSize(QtCore.QSize(50, 30))
        self.teamB_logo.setMaximumSize(QtCore.QSize(50, 30))
        self.teamB_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamB_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamB_logo.setObjectName("teamB_logo")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.teamB_logo)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblTeamB_logo = QtWidgets.QLabel(self.teamB_logo)
        self.lblTeamB_logo.setStyleSheet(f"background-image: url();\n"
                                         "background-repeat: no-repeat;\n"
                                         "background-position: center;\n"
                                         "")
        self.lblTeamB_logo.setMinimumSize(QtCore.QSize(50, 30))
        self.lblTeamB_logo.setMaximumSize(QtCore.QSize(50, 30))
        # lblTeamB_logo = self.lblTeamB_logo
        # pixmap = QPixmap('riomaior_logo.jpg')
        # lblTeamB_logo.setPixmap(pixmap)
        # self.lblTeamB_logo.setText("")
        # self.lblTeamB_logo.setObjectName("lblTeamB_logo")
        self.horizontalLayout_6.addWidget(self.lblTeamB_logo)
        self.horizontalLayout_2.addWidget(self.teamB_logo)
        self.timer = QtWidgets.QFrame(self.main_frame)
        self.timer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timer.setStyleSheet("")
        self.timer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timer.setObjectName("timer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.timer)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblTimer = QtWidgets.QLabel(self.timer)
        self.lblTimer.setMinimumSize(QtCore.QSize(102, 0))
        self.lblTimer.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("QuiverItal")
        font.setPointSize(22)
        self.lblTimer.setFont(font)
        self.lblTimer.setStyleSheet("color: rgb(200, 200, 200);\n"
                                    "background-color: rgb(60, 60, 60);\n"
                                    "border-radius: 10px;\n"
                                    "padding-bottom: 5px;\n"
                                    "padding-right: 0px;")
        self.lblTimer.setText("")
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName("lblTimer")
        self.horizontalLayout_9.addWidget(self.lblTimer)
        self.lblPer = QtWidgets.QLabel(self.timer)
        self.lblPer.setMinimumSize(QtCore.QSize(50, 0))
        self.lblPer.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("QuiverItal")
        font.setPointSize(22)
        self.lblPer.setFont(font)
        self.lblPer.setStyleSheet("color: rgb(200, 200, 200);\n"
                                  "background-color: rgb(60, 60, 60);\n"
                                  "border-radius: 10px;\n"
                                  "padding-bottom: 5px;\n"
                                  "padding-right: 0px;")
        self.lblPer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPer.setObjectName("lblPer")
        self.horizontalLayout_9.addWidget(self.lblPer)
        self.horizontalLayout_2.addWidget(self.timer)
        self.verticalLayout.addWidget(self.main_frame)
        self.frame_buttons = QtWidgets.QFrame(self.main)
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnframe1 = QtWidgets.QFrame(self.frame_buttons)
        self.btnframe1.setMaximumSize(QtCore.QSize(121, 16777215))
        self.btnframe1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnframe1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnframe1.setObjectName("btnframe1")
        self.horizontalLayout.addWidget(self.btnframe1)
        self.btnframe3 = QtWidgets.QFrame(self.frame_buttons)
        self.btnframe3.setMinimumSize(QtCore.QSize(80, 0))
        self.btnframe3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnframe3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnframe3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnframe3.setObjectName("btnframe3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.btnframe3)
        self.verticalLayout_2.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.btnframe3)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.btnA_plus2 = QtWidgets.QPushButton(self.btnframe3)
        self.btnA_plus2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnA_plus2.setFont(font)
        self.btnA_plus2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnA_plus2.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(40, 40, 40);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(55, 200, 55);\n"
                                      "    border: 2px solid rgb(80, 180, 80);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(55, 55, 55);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(65, 210, 65);\n"
                                      "    border: 2px solid rgb(90, 190, 90);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(30, 30, 30);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(65, 190, 65);\n"
                                      "    border: 2px solid rgb(70, 170, 70);\n"
                                      "}\n"
                                      "")
        self.btnA_plus2.setObjectName("btnA_plus2")
        self.verticalLayout_2.addWidget(self.btnA_plus2)
        self.btnA_plus3 = QtWidgets.QPushButton(self.btnframe3)
        self.btnA_plus3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnA_plus3.setFont(font)
        self.btnA_plus3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnA_plus3.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(40, 40, 40);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(80, 200, 80);\n"
                                      "    border: 2px solid rgb(110, 180, 110);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(55, 55, 55);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(90, 210, 90);\n"
                                      "    border: 2px solid rgb(120, 190, 120);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(30, 30, 30);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(70, 190, 70);\n"
                                      "    border: 2px solid rgb(100, 170, 100);\n"
                                      "}")
        self.btnA_plus3.setObjectName("btnA_plus3")
        self.verticalLayout_2.addWidget(self.btnA_plus3)
        self.btnA_plus1 = QtWidgets.QPushButton(self.btnframe3)
        self.btnA_plus1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnA_plus1.setFont(font)
        self.btnA_plus1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnA_plus1.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(40, 40, 40);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(80, 200, 80);\n"
                                      "    border: 2px solid rgb(110, 180, 110);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(55, 55, 55);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(90, 210, 90);\n"
                                      "    border: 2px solid rgb(120, 190, 120);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(30, 30, 30);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(70, 190, 70);\n"
                                      "    border: 2px solid rgb(100, 170, 100);\n"
                                      "}")
        self.btnA_plus1.setObjectName("btnA_plus1")
        self.verticalLayout_2.addWidget(self.btnA_plus1)
        self.btnA_correction = QtWidgets.QPushButton(self.btnframe3)
        self.btnA_correction.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnA_correction.setFont(font)
        self.btnA_correction.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnA_correction.setStyleSheet("QPushButton {\n"
                                           "    border-radius: 10px;\n"
                                           "    background-color: rgb(40, 40, 40);\n"
                                           "    color: rgb(200, 30, 30);\n"
                                           "    padding-bottom: 4px;\n"
                                           "    border: 2px solid rgb(200, 60, 60);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    border-radius: 10px;\n"
                                           "    background-color: rgb(55, 55, 55);\n"
                                           "    color: rgb(210, 40, 40);\n"
                                           "    padding-bottom: 4px;\n"
                                           "    border: 2px solid rgb(210, 70, 70);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    border-radius: 10px;\n"
                                           "    background-color: rgb(30, 30, 30);\n"
                                           "    color: rgb(190, 20, 20);\n"
                                           "    padding-bottom: 4px;\n"
                                           "    border: 2px solid rgb(190, 50, 50);\n"
                                           "}")
        self.btnA_correction.setObjectName("btnA_correction")
        self.verticalLayout_2.addWidget(self.btnA_correction)
        self.horizontalLayout.addWidget(self.btnframe3)
        self.btnframe2 = QtWidgets.QFrame(self.frame_buttons)
        self.btnframe2.setMinimumSize(QtCore.QSize(80, 0))
        self.btnframe2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnframe2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnframe2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnframe2.setObjectName("btnframe2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.btnframe2)
        self.verticalLayout_3.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.btnframe2)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.btnB_plus2 = QtWidgets.QPushButton(self.btnframe2)
        self.btnB_plus2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnB_plus2.setFont(font)
        self.btnB_plus2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnB_plus2.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(40, 40, 40);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(55, 200, 55);\n"
                                      "    border: 2px solid rgb(80, 180, 80);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(55, 55, 55);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(65, 210, 65);\n"
                                      "    border: 2px solid rgb(90, 190, 90);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(30, 30, 30);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(65, 190, 65);\n"
                                      "    border: 2px solid rgb(70, 170, 70);\n"
                                      "}\n"
                                      "")
        self.btnB_plus2.setObjectName("btnB_plus2")
        self.verticalLayout_3.addWidget(self.btnB_plus2)
        self.btnB_plus3 = QtWidgets.QPushButton(self.btnframe2)
        self.btnB_plus3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnB_plus3.setFont(font)
        self.btnB_plus3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnB_plus3.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(40, 40, 40);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(80, 200, 80);\n"
                                      "    border: 2px solid rgb(110, 180, 110);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(55, 55, 55);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(90, 210, 90);\n"
                                      "    border: 2px solid rgb(120, 190, 120);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(30, 30, 30);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(70, 190, 70);\n"
                                      "    border: 2px solid rgb(100, 170, 100);\n"
                                      "}")
        self.btnB_plus3.setObjectName("btnB_plus3")
        self.verticalLayout_3.addWidget(self.btnB_plus3)
        self.btnB_plus1 = QtWidgets.QPushButton(self.btnframe2)
        self.btnB_plus1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnB_plus1.setFont(font)
        self.btnB_plus1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnB_plus1.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(40, 40, 40);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(80, 200, 80);\n"
                                      "    border: 2px solid rgb(110, 180, 110);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(55, 55, 55);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(90, 210, 90);\n"
                                      "    border: 2px solid rgb(120, 190, 120);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-radius: 10px;\n"
                                      "    background-color: rgb(30, 30, 30);\n"
                                      "    padding-bottom: 4px;\n"
                                      "    color: rgb(70, 190, 70);\n"
                                      "    border: 2px solid rgb(100, 170, 100);\n"
                                      "}")
        self.btnB_plus1.setObjectName("btnB_plus1")
        self.verticalLayout_3.addWidget(self.btnB_plus1)
        self.btnB_correction = QtWidgets.QPushButton(self.btnframe2)
        self.btnB_correction.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnB_correction.setFont(font)
        self.btnB_correction.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnB_correction.setStyleSheet("QPushButton {\n"
                                           "    border-radius: 10px;\n"
                                           "    background-color: rgb(40, 40, 40);\n"
                                           "    color: rgb(200, 30, 30);\n"
                                           "    padding-bottom: 4px;\n"
                                           "    border: 2px solid rgb(200, 60, 60);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    border-radius: 10px;\n"
                                           "    background-color: rgb(55, 55, 55);\n"
                                           "    color: rgb(210, 40, 40);\n"
                                           "    padding-bottom: 4px;\n"
                                           "    border: 2px solid rgb(210, 70, 70);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    border-radius: 10px;\n"
                                           "    background-color: rgb(30, 30, 30);\n"
                                           "    color: rgb(190, 20, 20);\n"
                                           "    padding-bottom: 4px;\n"
                                           "    border: 2px solid rgb(190, 50, 50);\n"
                                           "}")
        self.btnB_correction.setObjectName("btnB_correction")
        self.verticalLayout_3.addWidget(self.btnB_correction)
        self.horizontalLayout.addWidget(self.btnframe2)
        self.frame_3 = QtWidgets.QFrame(self.frame_buttons)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.btnframe4 = QtWidgets.QFrame(self.frame_buttons)
        self.btnframe4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnframe4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnframe4.setObjectName("btnframe4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.btnframe4)
        self.verticalLayout_4.setContentsMargins(80, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.btnframe4)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4.addWidget(self.frame_4)
        self.btnTO = QtWidgets.QPushButton(self.btnframe4)
        self.btnTO.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnTO.setFont(font)
        self.btnTO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTO.setStyleSheet("QPushButton {\n"
                                 "    border-radius: 10px;\n"
                                 "    background-color: rgb(40, 40, 40);\n"
                                 "    padding-bottom: 4px;\n"
                                 "    color: rgb(200, 200, 200);\n"
                                 "    border: 2px solid rgb(180, 180, 180);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    border-radius: 10px;\n"
                                 "    background-color: rgb(55, 55, 55);\n"
                                 "    padding-bottom: 4px;\n"
                                 "    color: rgb(210, 210, 210);\n"
                                 "    border: 2px solid rgb(190, 190, 190);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    border-radius: 10px;\n"
                                 "    background-color: rgb(30, 30, 30);\n"
                                 "    padding-bottom: 4px;\n"
                                 "    color: rgb(190, 190, 190);\n"
                                 "    border: 2px solid rgb(170, 170, 170);\n"
                                 "}")
        self.btnTO.setObjectName("btnTO")
        self.verticalLayout_4.addWidget(self.btnTO)
        self.btnP = QtWidgets.QPushButton(self.btnframe4)
        self.btnP.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnP.setFont(font)
        self.btnP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnP.setStyleSheet("QPushButton {\n"
                                "    border-radius: 10px;\n"
                                "    background-color: rgb(40, 40, 40);\n"
                                "    padding-bottom: 4px;\n"
                                "    color: rgb(200, 200, 200);\n"
                                "    border: 2px solid rgb(180, 180, 180);\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    border-radius: 10px;\n"
                                "    background-color: rgb(55, 55, 55);\n"
                                "    padding-bottom: 4px;\n"
                                "    color: rgb(210, 210, 210);\n"
                                "    border: 2px solid rgb(190, 190, 190);\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    border-radius: 10px;\n"
                                "    background-color: rgb(30, 30, 30);\n"
                                "    padding-bottom: 4px;\n"
                                "    color: rgb(190, 190, 190);\n"
                                "    border: 2px solid rgb(170, 170, 170);\n"
                                "}")
        self.btnP.setObjectName("btnP")
        self.verticalLayout_4.addWidget(self.btnP)
        self.btnPplus = QtWidgets.QPushButton(self.btnframe4)
        self.btnPplus.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnPplus.setFont(font)
        self.btnPplus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPplus.setStyleSheet("QPushButton {\n"
                                    "    border-radius: 10px;\n"
                                    "    background-color: rgb(40, 40, 40);\n"
                                    "    padding-bottom: 4px;\n"
                                    "    color: rgb(55, 200, 55);\n"
                                    "    border: 2px solid rgb(80, 180, 80);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    "    border-radius: 10px;\n"
                                    "    background-color: rgb(55, 55, 55);\n"
                                    "    padding-bottom: 4px;\n"
                                    "    color: rgb(65, 210, 65);\n"
                                    "    border: 2px solid rgb(90, 190, 90);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    border-radius: 10px;\n"
                                    "    background-color: rgb(30, 30, 30);\n"
                                    "    padding-bottom: 4px;\n"
                                    "    color: rgb(65, 190, 65);\n"
                                    "    border: 2px solid rgb(70, 170, 70);\n"
                                    "}\n"
                                    "")
        self.btnPplus.setObjectName("btnPplus")
        self.verticalLayout_4.addWidget(self.btnPplus)
        self.btnPminus = QtWidgets.QPushButton(self.btnframe4)
        self.btnPminus.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnPminus.setFont(font)
        self.btnPminus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPminus.setStyleSheet("QPushButton {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(40, 40, 40);\n"
                                     "    color: rgb(200, 30, 30);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    border: 2px solid rgb(200, 60, 60);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(55, 55, 55);\n"
                                     "    color: rgb(210, 40, 40);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    border: 2px solid rgb(210, 70, 70);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(30, 30, 30);\n"
                                     "    color: rgb(190, 20, 20);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    border: 2px solid rgb(190, 50, 50);\n"
                                     "}")
        self.btnPminus.setObjectName("btnPminus")
        self.verticalLayout_4.addWidget(self.btnPminus)
        self.horizontalLayout.addWidget(self.btnframe4)
        self.verticalLayout.addWidget(self.frame_buttons)
        self.dirs = QtWidgets.QFrame(self.main)
        self.dirs.setMaximumSize(QtCore.QSize(16777215, 80))
        self.dirs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dirs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dirs.setObjectName("dirs")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.dirs)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.dirs)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lTeamLogo = QtWidgets.QTextEdit(self.frame_5)
        self.lTeamLogo.setStyleSheet("QTextEdit {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(40, 40, 40);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(200, 200, 200);\n"
                                     "    border: 2px solid rgb(180, 180, 180);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:hover {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(55, 55, 55);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(210, 210, 210);\n"
                                     "    border: 2px solid rgb(190, 190, 190);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(30, 30, 30);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(190, 190, 190);\n"
                                     "    border: 2px solid rgb(170, 170, 170);\n"
                                     "}")
        self.lTeamLogo.setObjectName("lTeamLogo")
        self.verticalLayout_5.addWidget(self.lTeamLogo)
        self.rTeamLogo = QtWidgets.QTextEdit(self.frame_5)
        self.rTeamLogo.setStyleSheet("QTextEdit {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(40, 40, 40);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(200, 200, 200);\n"
                                     "    border: 2px solid rgb(180, 180, 180);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:hover {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(55, 55, 55);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(210, 210, 210);\n"
                                     "    border: 2px solid rgb(190, 190, 190);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(30, 30, 30);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(190, 190, 190);\n"
                                     "    border: 2px solid rgb(170, 170, 170);\n"
                                     "}")
        self.rTeamLogo.setObjectName("rTeamLogo")
        self.verticalLayout_5.addWidget(self.rTeamLogo)
        self.horizontalLayout_10.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.dirs)
        self.frame_7.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lTeamName = QtWidgets.QTextEdit(self.frame_7)
        self.lTeamName.setStyleSheet("QTextEdit {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(40, 40, 40);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(200, 200, 200);\n"
                                     "    border: 2px solid rgb(180, 180, 180);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:hover {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(55, 55, 55);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(210, 210, 210);\n"
                                     "    border: 2px solid rgb(190, 190, 190);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(30, 30, 30);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(190, 190, 190);\n"
                                     "    border: 2px solid rgb(170, 170, 170);\n"
                                     "}")
        self.lTeamName.setObjectName("lTeamName")
        self.verticalLayout_6.addWidget(self.lTeamName)
        self.rTeamName = QtWidgets.QTextEdit(self.frame_7)
        self.rTeamName.setStyleSheet("QTextEdit {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(40, 40, 40);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(200, 200, 200);\n"
                                     "    border: 2px solid rgb(180, 180, 180);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:hover {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(55, 55, 55);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(210, 210, 210);\n"
                                     "    border: 2px solid rgb(190, 190, 190);\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus {\n"
                                     "    border-radius: 10px;\n"
                                     "    background-color: rgb(30, 30, 30);\n"
                                     "    padding-bottom: 4px;\n"
                                     "    color: rgb(190, 190, 190);\n"
                                     "    border: 2px solid rgb(170, 170, 170);\n"
                                     "}")
        self.rTeamName.setObjectName("rTeamName")
        self.verticalLayout_6.addWidget(self.rTeamName)
        self.horizontalLayout_10.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.dirs)
        self.frame_6.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnSend = QtWidgets.QPushButton(self.frame_6)
        self.btnSend.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnSend.setFont(font)
        self.btnSend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSend.setStyleSheet("QPushButton {\n"
                                   "    border-radius: 10px;\n"
                                   "    background-color: rgb(40, 40, 40);\n"
                                   "    padding-bottom: 4px;\n"
                                   "    color: rgb(200, 200, 200);\n"
                                   "    border: 2px solid rgb(180, 180, 180);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   "    border-radius: 10px;\n"
                                   "    background-color: rgb(55, 55, 55);\n"
                                   "    padding-bottom: 4px;\n"
                                   "    color: rgb(210, 210, 210);\n"
                                   "    border: 2px solid rgb(190, 190, 190);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    border-radius: 10px;\n"
                                   "    background-color: rgb(30, 30, 30);\n"
                                   "    padding-bottom: 4px;\n"
                                   "    color: rgb(190, 190, 190);\n"
                                   "    border: 2px solid rgb(170, 170, 170);\n"
                                   "}")
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_11.addWidget(self.btnSend)
        self.horizontalLayout_10.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.dirs)
        MainWindow.setCentralWidget(self.main)

        #
        # CONNECTIONS
        #

        self.btnA_correction.clicked.connect(self.correctionTeamA)
        self.btnA_plus1.clicked.connect(self.addOneTeamA)
        self.btnA_plus2.clicked.connect(self.addTwoTeamA)
        self.btnA_plus3.clicked.connect(self.addThreeTeamA)

        self.btnB_correction.clicked.connect(self.correctionTeamB)
        self.btnB_plus1.clicked.connect(self.addOneTeamB)
        self.btnB_plus2.clicked.connect(self.addTwoTeamB)
        self.btnB_plus3.clicked.connect(self.addThreeTeamB)

        self.btnP.clicked.connect(self.Per)
        self.btnTO.clicked.connect(self.TO)
        self.btnPplus.clicked.connect(self.addOnePer)
        self.btnPminus.clicked.connect(self.minusOnePer)

        self.btnSend.clicked.connect(self.addNamesAndLogos)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTeamA_score.setText(_translate("MainWindow", "0"))
        self.lblTeamB_score.setText(_translate("MainWindow", "0"))
        self.lblTeamB_name.setText(_translate("MainWindow", ""))
        self.lblPer.setText(_translate("MainWindow", "1"))
        self.btnA_plus2.setText(_translate("MainWindow", "+2"))
        self.btnA_plus3.setText(_translate("MainWindow", "+3"))
        self.btnA_plus1.setText(_translate("MainWindow", "+1"))
        self.btnA_correction.setText(_translate("MainWindow", "-1"))
        self.btnB_plus2.setText(_translate("MainWindow", "+2"))
        self.btnB_plus3.setText(_translate("MainWindow", "+3"))
        self.btnB_plus1.setText(_translate("MainWindow", "+1"))
        self.btnB_correction.setText(_translate("MainWindow", "-1"))
        self.btnTO.setText(_translate("MainWindow", "TO"))
        self.btnP.setText(_translate("MainWindow", "P"))
        self.btnPplus.setText(_translate("MainWindow", "+"))
        self.btnPminus.setText(_translate("MainWindow", "-"))
        self.lTeamLogo.setPlaceholderText(_translate(
            "MainWindow", "Enter here the left team logo directory..."))
        self.rTeamLogo.setPlaceholderText(_translate(
            "MainWindow", "Enter here the right team logo directory..."))
        self.lTeamName.setPlaceholderText(_translate(
            "MainWindow", "3-letter left team name..."))
        self.rTeamName.setPlaceholderText(_translate(
            "MainWindow", "6-letter right team name..."))
        self.btnSend.setText(_translate("MainWindow", "SEND"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
